# Site settings
title: Biomechanical ToolKit
description: "Open-source project to process and analyze motion capture data"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://biomechanical-toolkit.github.io" # the base hostname & protocol for your site
permalink: /news/:year/:month/:day/:title/
twitter_username: btkwww
github_username: biomechanical-toolkit

highlighter: rouge
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
include: docs # For Doyxgen filename starting with a underscore
