# Site settings
title: Biomechanical ToolKit
description: "Open-source project to process and analyze motion capture data"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://biomechanical-toolkit.github.io" # the base hostname & protocol for your site
permalink: /news/:year/:month/:day/:title/
twitter_username: btkwww
github_username: biomechanical-toolkit

highlighter: rouge
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# For Doyxgen filename starting with a underscore
include:
  - _advanced_tutorial.html
  - _build_instructions.html
  - _developer.html
  - _file_format_supported.html
  - _getting_started.html
  - _license.html
  - _f_a_q.html
  - _file_format_supported.html
  - _structure_fieldname_format.html
  - _tutorial.html
  - _warnings_i_d.html
  - _build_instructions.html
  - _file_format_supported.html
  - _getting_started.html
  - _license.html
  - _mokka3_d_view.html
  - _mokka_cmd_line.html
  - _mokka_import_assistant.html
  - _mokka_intro.html
  - _mokka_menu_bar.html
  - _mokka_menu_bar.js
  - _mokka_model_pane.html
  - _mokka_preferences.html
  - _mokka_release_note.html
  - _mokka_shortcut.html
  - _mokka_time_bar.html
  - _mokka_tools.html
  - _mokka_tutorial.html
  - _mokka_tutorial.js
  - _mokka_tutorial__add_remove_event.html
  - _mokka_tutorial__change_color_marker.html
  - _mokka_tutorial__create_cycle_definition.html
  - _mokka_tutorial__create_new_segment.html
  - _mokka_tutorial__create_save_new_configuration.html
  - _mokka_tutorial__edit_event.html
  - _mokka_tutorial__watch_video.html
  - _mokka_view.html
  - _mokka_working.html
  - _mokka_working.js