# Site settings
title: Biomechanical ToolKit
description: "Open-source project to process and analyze motion capture data"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://biomechanical-toolkit.github.io" # the base hostname & protocol for your site
permalink: /news/:year/:month/:day/:title/
twitter_username: btkwww
github_username: biomechanical-toolkit

highlighter: rouge
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# For Doyxgen filename starting with a underscore
include:
 - docs/API/_advanced_tutorial.html
 - docs/API/_build_instructions.html
 - docs/API/_developer.html
 - docs/API/_file_format_supported.html
 - docs/API/_getting_started.html
 - docs/API/_license.html
 - docs/Wrapping/Matlab/_f_a_q.html
 - docs/Wrapping/Matlab/_file_format_supported.html
 - docs/Wrapping/Matlab/_structure_fieldname_format.html
 - docs/Wrapping/Matlab/_tutorial.html
 - docs/Wrapping/Matlab/_warnings_i_d.html
 - docs/Wrapping/Python/_build_instructions.html
 - docs/Wrapping/Python/_file_format_supported.html
 - docs/Wrapping/Python/_getting_started.html
 - docs/Wrapping/Python/_license.html